/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_drcom_drsniffer_DrSnifferJni */

#ifndef _Included_com_drcom_drsniffer_DrSnifferJni
#define _Included_com_drcom_drsniffer_DrSnifferJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_drcom_drsniffer_DrSnifferJni
 * Method:    IsRoot
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_drcom_drsniffer_DrSnifferJni_IsRoot
  (JNIEnv *, jobject);

/*
 * Class:     com_drcom_drsniffer_DrSnifferJni
 * Method:    ReleaseDrSniffer
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_drcom_drsniffer_DrSnifferJni_ReleaseDrSniffer
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_drcom_drsniffer_DrSnifferJni
 * Method:    SystemComandExcute
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_drcom_drsniffer_DrSnifferJni_SystemComandExcute
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_drcom_drsniffer_DrSnifferJni
 * Method:    SystemComandExcuteWithRoot
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_drcom_drsniffer_DrSnifferJni_SystemComandExcuteWithRoot
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_drcom_drsniffer_DrSnifferJni
 * Method:    StartServer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_drcom_drsniffer_DrSnifferJni_StartServer
  (JNIEnv *, jobject);

/*
 * Class:     com_drcom_drsniffer_DrSnifferJni
 * Method:    StopServer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_drcom_drsniffer_DrSnifferJni_StopServer
  (JNIEnv *, jobject);

/*
 * Class:     com_drcom_drsniffer_DrSnifferJni
 * Method:    GetOnlineClientList
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_drcom_drsniffer_DrSnifferJni_GetOnlineClientList
  (JNIEnv *, jobject);

/*
 * Class:     com_drcom_drsniffer_DrSnifferJni
 * Method:    SendCommandToClient
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_drcom_drsniffer_DrSnifferJni_SendCommandToClient
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
