/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kk_sniffer_SnifferJni */

#ifndef _Included_org_kk_sniffer_SnifferJni
#define _Included_org_kk_sniffer_SnifferJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kk_sniffer_SnifferJni
 * Method:    IsRoot
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_kk_sniffer_SnifferJni_IsRoot
  (JNIEnv *, jobject);

/*
 * Class:     org_kk_sniffer_SnifferJni
 * Method:    ReleaseDrSniffer
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kk_sniffer_SnifferJni_ReleaseDrSniffer
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_kk_sniffer_SnifferJni
 * Method:    SystemComandExcute
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kk_sniffer_SnifferJni_SystemComandExcute
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kk_sniffer_SnifferJni
 * Method:    SystemComandExcuteWithRoot
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kk_sniffer_SnifferJni_SystemComandExcuteWithRoot
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
